import Navbar from "@/components/Navbar";
import Head from "next/head";
import React, { useState } from "react";

export default function Home() {

  const [darkMode, setDarkMode] = useState(false)

  const toggleMode = () => {
    setDarkMode(!darkMode)
  }

  return (
    <div className={darkMode?'dark':''}>
      <Head>
        <title>Dictionary</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Navbar toggleMode={toggleMode} darkMode={darkMode}/>
      </main>
    </div>
  );
}
