import Navbar from "@/components/Navbar";
import Search from "@/components/Search";
import Head from "next/head";
import React, { useState, useRef } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [font, setFont] = useState("serif");
  const fontRef = useRef();

  const toggleMode = () => {
    setDarkMode(!darkMode);
  };


  const changeFont = () => {
    const selectedValue = fontRef.current.value;
    setFont(selectedValue);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dictionary</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`bg-white dark:bg-black font-${font}`}>
        <section className={`min-h-screen `}>
          <Navbar
            toggleMode={toggleMode}
            darkMode={darkMode}
            fontRef={fontRef}
            font={font}
            changeFont={changeFont}
          />
          <Search darkMode={darkMode} />
        </section>
      </main>
    </div>
  );
}
